title: Sage.Edcuation
description: Sage Education is an innovative platform dedicated to empowering
  educators and learners to effectively harness artificial intelligence (AI) in
  educational settings. It offers a comprehensive suite of tools and resources
  designed to facilitate the creation of cutting-edge AI solutions, emphasizing
  data security, critical thinking, and a maker mindset.
author: Sage Team
logo: https://sage.education/images/sage.education_logo.svg
contact:
  email: info@sage.education
  phone: "935206957"
address:
  street: Lomba Dos Frades, No. 44
  city: PRAIA DO ALMOXARIFE
  zip: 9900-451
  country: Portugal
