logo_url:
  https://startr.style/logo.png

#backend:
#  name: git-gateway
#  branch: master # Branch to update (optional; defaults to master)
#  local_backend: true # Use the local backend for development

backend:
  name: github
  repo: Startr/WEB-Sage.Education
  branch: master # Branch to update (optional; defaults to master)
  site_domain: https://sage.education
  base_url: https://sage.education
  auth_endpoint: /api/auth

local_backend:
  url: http://192.168.1.103:8081/api/v1 # URL to the local backend
  allowed_hosts: ["192.168.1.103"] # List of allowed hosts

media_folder: "static/uploads" # Path to where uploaded files will be stored in your repo
public_folder: "/uploads" # Path users will access the files from on the deployed site

i18n:
  structure: multiple_folders
  locales: [en, fr, de, pt]

collections:
  - name: "site_settings" # Used in routes, e.g., /admin/collections/site_settings
    label: "Site Settings" # Used in the UI
    files: # The files in the collection
      - file: "src/_data/site.yaml" # The path to the file
        label: "Site Data" # Used in the UI
        name: "site_data" # Used in the UI
        fields: # The fields for the file
          - { label: "Title", name: "title", widget: "string", i18n: true }
          - { label: "Description", name: "description", widget: "text", i18n: true }
          - { label: "Author", name: "author", widget: "string", i18n: true }
          # Select logo from media library
          - { label: "Logo", name: "logo", widget: "image", i18n: true, required: false }
          - { label: "Menu", name: "menu", widget: "list", fields: [ { label: "Title", name: "title", widget: "string", i18n: true }, { label: "URL", name: "url", widget: "string", i18n: true } ], required: false }
          - { label: "Footer", name: "footer", widget: "text", i18n: true, required: false }
          - { label: "Social Links", name: "social", widget: "list", fields: [ { label: "Title", name: "title", widget: "string", i18n: true }, { label: "URL", name: "url", widget: "string", i18n: true } ],required: false } 
          - { label: "Contact", name: "contact", widget: "object", fields: [ { label: "Email", name: "email", widget: "string", i18n: true }, { label: "Phone", name: "phone", widget: "string", i18n: true } ] }
          - { label: "Address", name: "address", widget: "object", fields: [ { label: "Street", name: "street", widget: "string", i18n: true }, { label: "City", name: "city", widget: "string", i18n: true }, { label: "Zip", name: "zip", widget: "string", i18n: true }, { label: "Country", name: "country", widget: "string", i18n: true } ] }
      - file: "src/_data/reading.yaml" # Path to emulate Wordpress's reading settings eg home page display
        label: "Reading Settings" # Used in the UI
        name: "reading_settings" # Used in the UI
        fields: # The fields for the file
          - { label: "Front Page", name: "front_page", widget: "relation", collection: "pages", value_field: "title", search_fields: ["title"], i18n: true }
          - { label: "Posts Page", name: "posts_page", widget: "relation", collection: "pages", value_field: "title", search_fields: ["title"], i18n: true }
          - { label: "Posts Per Page", name: "posts_per_page", widget: "number", i18n: true }
          - { label: "Default Layout", name: "default_layout", widget: "hidden", default: "layouts/blog.njk", i18n: true }
          - { label: "Default Tags", name: "default_tags", widget: "list", default: "education", i18n: true }
          # Syndication feeds
          - { label: "Posts per feed", name: "posts_per_feed", widget: "number", default: 10, i18n: true }
          - { label: "Full text or Summary", name: "full_text_or_summary", widget: "select", options: ["full", "summary"], default: "summary", i18n: true }
          - { label: "Search Engine Visibility", name: "search_engine_visibility", widget: "boolean", default: true, i18n: true }
      - file: "src/_data/pricing.yaml"
        name: "pricing_data"
        label: "Pricing Data"
        fields:
          - { label: "Heading", name: "heading", widget: "string", i18n: true }
          - { label: "Subheading", name: "subheading", widget: "string", i18n: true }
          - { label: "Description", name: "description", widget: "text", i18n: true }
          - { label: "Offer a Deal", name: "deal", widget: "boolean", default: true, i18n: true }
          - label: "Deal Descriptions"
            name: "deal_description"
            widget: "list"
            fields:
              - {label: "title", name: "title", widget: "string", i18n: true}
              - {label: "subtitle", name: "subtitle", widget: "string", i18n: true}
          - label: "Offers"
            name: "offers"
            widget: "list"
            summary: '{{fields.name}}'
            fields:
              - {label: "Public", name: "public", widget: "boolean", default: true}
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Price", name: "price", widget: "number", default: 4.89}
              - {label: "Deal Price", name: "deal_price", widget: "number", default: 2.99}
              - {label: "Currency", name: "currency", widget: "string", default: "USD"}
              - {label: "Description", name: "description", widget: "text"}
              - label: "Features"
                name: "features"
                widget: "list"
                fields:
                  - {label: "Feature", name: "feature", widget: "string"}
                  - {label: "Description", name: "description", widget: "text"}
                  - {label: "Available", name: "available", widget: "boolean", default: true}
                  - {label: "Available as part of deal", name: "deal_available", widget: "boolean", default: true}
              - { label: "Start Date", name: "start_date", widget: "datetime",i18n: duplicate }
              - { label: "End Date", name: "end_date", widget: "datetime",i18n: duplicate }
              - { label: "Publish Date", name: "date", widget: "datetime",i18n: duplicate }
  - name: "pages" # Used in routes, e.g., /admin/collections/pages
    label: "Pages" # Used in the UI
    folder: "src/pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    i18n: true
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/base.njk" }
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Publish Date", name: "date", widget: "datetime", i18n: duplicate }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/posts/blog" # The path to the folder where the documents are stored  
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    i18n: true
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/blog.njk" }
      - { label: "Title", name: "title", widget: "string", i18n: true}
      - { label: "Tags", name: "tags", widget: "list", default: "education" }
      - { label: "Publish Date", name: "date", widget: "datetime",i18n: duplicate }
      - { label: "Rating (scale of 1-5)", name: "rating", widget: "number", default: 5, i18n: duplicate }
      - { label: "Summary", name: "summary",widget: "markdown", i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
